import type { Migration } from '../migrator'

/**
 * 003 — Chart Evidence / Trade Media. See docs/TRADE_MEDIA.md and
 * docs/DATABASE_SCHEMA.md §19.
 *
 * Metadata only: image bytes live under userData/media/ as files, never as a
 * SQLite BLOB. `managed_path` is a path RELATIVE to that media root (never an
 * absolute or user-controlled path), generated by Solid Skill and never
 * derived from user input. Exactly one of (trade_id, analytical_date) is set,
 * matching owner_type — a Trade image and a Day image are never conflated.
 *
 * Rows are otherwise immutable once written (no UPDATE path is exposed for
 * anything but `is_featured`); a changed caption is a delete + re-add.
 * Deletion is a repository-level DELETE plus a file removal in the media
 * service, never a schema trigger, since a file missing on disk must not
 * block the DB row from being removed.
 *
 * `is_featured` (Checkpoint 014, same migration since 003 was not yet
 * committed when the need appeared) marks the one Trade media item used as
 * the Overview's Chart Evidence visual. Trade-level only — a Day media row
 * can never be featured (CHECK). At most one featured row per Trade (partial
 * UNIQUE index). This is the one column allowed to change after insert; see
 * docs/TRADE_MEDIA.md §18.
 */
export const migration003: Migration = {
  version: 3,
  name: 'trade_media',
  sql: `
CREATE TABLE trade_media (
  id              TEXT PRIMARY KEY,
  owner_type      TEXT NOT NULL CHECK (owner_type IN ('TRADE', 'DAY')),
  trade_id        TEXT REFERENCES trades (id),
  account_id      TEXT NOT NULL REFERENCES accounts (id),
  analytical_date TEXT CHECK (analytical_date IS NULL OR analytical_date GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]'),
  managed_path    TEXT NOT NULL CHECK (length(managed_path) > 0),
  format          TEXT NOT NULL CHECK (format IN ('PNG', 'JPEG', 'WEBP')),
  timeframe       TEXT NOT NULL CHECK (timeframe IN ('M1','M3','M5','M15','M30','H1','H2','H4','D1','W1','OTHER')),
  stage           TEXT NOT NULL CHECK (stage IN ('PRE_TRADE','ENTRY','MANAGEMENT','EXIT','POST_TRADE')),
  caption         TEXT,
  is_featured     INTEGER NOT NULL DEFAULT 0 CHECK (is_featured IN (0, 1)),
  created_at      INTEGER NOT NULL,
  CHECK (
    (owner_type = 'TRADE' AND trade_id IS NOT NULL AND analytical_date IS NULL) OR
    (owner_type = 'DAY'   AND trade_id IS NULL     AND analytical_date IS NOT NULL)
  ),
  CHECK (owner_type = 'TRADE' OR is_featured = 0),
  FOREIGN KEY (trade_id, account_id) REFERENCES trades (id, account_id)
) STRICT;

CREATE INDEX trade_media_by_trade ON trade_media (trade_id, created_at) WHERE trade_id IS NOT NULL;
CREATE INDEX trade_media_by_day ON trade_media (account_id, analytical_date, created_at) WHERE analytical_date IS NOT NULL;

-- At most one featured row per Trade.
CREATE UNIQUE INDEX trade_media_featured_unique ON trade_media (trade_id) WHERE is_featured = 1;

-- Metadata rows are append/delete only; a caption or classification change is
-- a delete + re-add, so history of what was attached when never silently
-- drifts. "OF (...)" scopes the trigger to exactly those columns, so an
-- UPDATE that touches only is_featured is unaffected and does not abort.
CREATE TRIGGER trade_media_no_update
BEFORE UPDATE OF owner_type, trade_id, account_id, analytical_date, managed_path, format, timeframe, stage, caption, created_at ON trade_media
BEGIN
  SELECT RAISE(ABORT, 'trade media metadata is immutable; delete and re-add instead');
END;
`
}
